// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'cell--focused': string;
  'cell__input': string;
  'cell__input--marked': string;
  'cell__mark': string;
  'cell__mark--centre': string;
  'cell__mark--corner': string;
}
declare const cssExports: CssExports;
export = cssExports;
