// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sudoku-monster': string;
  'sudoku-monster__banner': string;
  'sudoku-monster__game': string;
}
declare const cssExports: CssExports;
export = cssExports;
