// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'controls__bottom': string;
  'controls__button': string;
  'controls__button--centre': string;
  'controls__button--corner': string;
  'controls__button--delete': string;
  'controls__button--mode-centre': string;
  'controls__button--mode-corner': string;
  'controls__button--mode-normal': string;
  'controls__button--normal': string;
  'controls__button--value': string;
  'controls__button--value-1': string;
  'controls__button--value-2': string;
  'controls__button--value-3': string;
  'controls__button--value-4': string;
  'controls__button--value-5': string;
  'controls__button--value-6': string;
  'controls__button--value-7': string;
  'controls__button--value-8': string;
  'controls__button--value-9': string;
}
declare const cssExports: CssExports;
export = cssExports;
