// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dialog': string;
  'dialog__backdrop': string;
  'dialog__banner': string;
  'dialog__button': string;
  'dialog__buttons': string;
  'dialog__close': string;
  'dialog__content': string;
  'dialog__title': string;
}
declare const cssExports: CssExports;
export = cssExports;
